### ISSUE TITLE
Where does acs2018_5yr_B01003_16000US0637134.geojson come from?

### ISSUE THREAD

**Issue by asg017** [datadesk/california-topojson-atlas#1]
It looks like a census population thing, but I'm not too sure where to find it. 

Context is that I'm trying to make a similar atlas for all states, but since this file only has California data, I'm not sure how to make something similar for other states.

**Comment by palewire** [comment]
I downloaded it manually from censusreporter.org. The whole country could be downloaded instead. Or a different source could be substituted. I'm not too picky about it.

**Comment by asg017** [comment]
ah, didn't even realize that this was in the README, my bad - thank you!

**Comment by palewire** [comment]
No sweat.
